Full-Stack Capstone - Booking an Appointment Application.
tan12082001/Vehicle-Booking-App-Backend pull request #33
Opened 2023-12-12 23:06 UTC by tan12082001

# Final group capstone - Book an Appointment

### Team ( 4 memebers ):

* @Simpleshaikh1 
* @tan12082001 
* @Wineshuga 
* @hetrox8 

### Project Information:

* [Book an Appointment application Business Requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md).
* [Project Progress Kanban Board](https://github.com/users/tan12082001/projects/4/views/1)

`NOTE: Working on two separate Repositories.`

### [Vehicle-Booking-App-Frontend](https://github.com/tan12082001/Vehicle-Booking-App-Frontend)
### [Vehicle-Booking-App-Frontend-Review-Pull-Request]()

### Instructions for Running the local version:

```
- bundle install
- secret_base_key generation
* rm credentials.yml.enc
* $ EDITOR="mate --wait" bin/rails credentials:edit

- configure database
* run `rails db:create`
* run `rails db:migrate`

- Rspec
* bundle exec rails db:schema:load RAILS_ENV=test
```

### Current Progress:
* Implemented 90% of core features.
#### Tasks left to complete:
- [ ] Implement styles for mobile and desktop versions.
- [ ] API Documentation.

### Kanban progress views:

#### Kanban board initial view:
![image](https://github.com/tan12082001/Vehical-Appointment-App-Backend/assets/81354942/f57bf009-046a-4c8a-817d-5b3cb163421c)

#### Kanban board final view:
![image](https://github.com/tan12082001/Vehicle-Booking-App-Backend/assets/81354942/8444f049-8e69-4887-ad6a-c88f6b3def65)

2023-12-13 09:59 UTC, Meltrust requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Tests are passing✔️
-  Good readme ✔️ 




#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-12-13 09:59 UTC, Meltrust commented on .dockerignore
> +# See https://docs.docker.com/engine/reference/builder/#dockerignore-file for more about ignoring files.
- [ ] The mobile view has not been implemented yet.  I understand this is a work in progress or a future update.


_tip:  If you feel you've completed 90% of the features, kindly say in your PR description what features will be left out to give a heads-up to the final evaluator and reviewers._

2023-12-14 15:04 UTC, Meltrust requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!








#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-12-14 19:28 UTC, tan12082001 commented on README.md
> +<a name="readme-top"></a>
> * [ ]  Please check the frontend review for the comments. 👍

Implemented the changes:

TestCases:
![image](https://github.com/tan12082001/Vehicle-Booking-App-Backend/assets/81354942/a45363fa-89fc-4425-969a-1063b0b3a22c)

2023-12-14 19:56 UTC, Meltrust approved these changes
# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight


- Superb job ✔️  



Cheers and Happy coding!👏👏👏


------

2023-12-14 20:02 UTC, merged